server:
  error:
    include-binging-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: FoodApp


## MYSQL CONNECTION
  datasource:
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:password}
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  ## Mail configuration
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:111}
    username: ${MAIL_USERNAME:smtp.example.com}
    password: ${MAIL_PASSWORD:smtp.example.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

## AWS Configuration
##aws:
##  s3:
##    region:
##    bicket:
##  accessKeyId:
##  secretKey:


jwt:
  secret-key: ${JWT_SECRET_KEY:jwtkey}