spring:
  application:
    name: FoodApp


## MYSQL CONNECTION
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username:
    password:
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update